# Generated by Django 5.2.6 on 2026-01-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='referred_by',
            new_name='sponser',
        ),
    ]
