# Generated by Django 5.2.6 on 2026-01-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_rename_referred_by_memberprofile_sponser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='referral_code',
            new_name='ref_id',
        ),
    ]
