# Generated by Django 5.2.6 on 2026-01-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_rename_referral_code_memberprofile_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
