# Generated by Django 5.2.6 on 2026-01-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_memberprofile_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrevenue',
            name='b3_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adminrevenue',
            name='b4_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adminrevenue',
            name='b5_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_5_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_already_placed_in_b1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='left_child_b3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_l_b3', to='matrix.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='left_child_b4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_l_b4', to='matrix.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='left_child_b5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_l_b5', to='matrix.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='right_child_b3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_r_b3', to='matrix.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='right_child_b4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_r_b4', to='matrix.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='right_child_b5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_r_b5', to='matrix.memberprofile'),
        ),
        migrations.AlterField(
            model_name='adminrevenue',
            name='b1_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminrevenue',
            name='b2_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
