# Generated by Django 5.2.6 on 2026-01-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_adminrevenue_b3_fees_adminrevenue_b4_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID / TxID'),
        ),
    ]
