# Generated by Django 5.2.6 on 2026-01-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_alter_memberprofile_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='sponser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referrals', to='matrix.memberprofile'),
        ),
    ]
