# Generated by Django 5.2.6 on 2026-01-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_alter_memberprofile_sponser'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='paid_referrals_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction ID / TxID'),
        ),
    ]
