# Generated by Django 5.2.6 on 2026-02-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_memberprofile_paid_referrals_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_position_locked',
            field=models.BooleanField(default=False),
        ),
    ]
