# Generated by Django 5.2.6 on 2026-02-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0010_memberprofile_is_position_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='board_1_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_2_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_3_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_4_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='board_5_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
