# Generated by Django 5.2.6 on 2026-02-02 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0011_memberprofile_board_1_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField(default=1)),
                ('position', models.IntegerField(blank=True, choices=[(1, 'Left'), (2, 'Right')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='matrix.matrixnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'board')},
            },
        ),
    ]
