# Generated by Django 5.2.6 on 2026-02-02 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0012_matrixnode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matrixnode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matrixnode',
            name='parent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_children', to='matrix.memberprofile'),
        ),
        migrations.AlterField(
            model_name='matrixnode',
            name='board',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matrixnode',
            name='position',
            field=models.IntegerField(choices=[(1, 'Left'), (2, 'Right')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='ref_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('AIRDROP', 'Airdrop'), ('CYCLE', 'Cycle Payout'), ('UPGRADE', 'Upgrade'), ('DEBIT', 'Deduction'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='matrixnode',
            name='parent',
        ),
    ]
